services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: